fix

diff --git a/lkm b/lkm
--- a/lkm
+++ b/lkm
@@ -1,6 +1,13 @@
 #!/bin/bash
 # lkm : a silly kernel module dev - build, load, unload - helper wrapper script
 # License: MIT
+# Kaiwan NB
+
+# Turn on unofficial Bash 'strict mode'! V useful
+# "Convert many kinds of hidden, intermittent, or subtle bugs into immediate, glaringly obvious errors"
+# ref: http://redsymbol.net/articles/unofficial-bash-strict-mode/
+set -euo pipefail
+
 unset ARCH
 unset CROSS_COMPILE
 name=$(basename "${0}")
@@ -11,17 +18,17 @@ name=$(basename "${0}")
 runcmd()
 {
 local SEP="------------------------------"
-[ $# -eq 0 ] && return
+[[ $# -eq 0 ]] && return
 echo "${SEP}
 $*
 ${SEP}"
 eval "$@"
-[ $? -ne 0 ] && echo " ^--[FAILED]"
+[[ $? -ne 0 ]] && echo " ^--[FAILED]"
 }
 
 ### "main" here
 
-[ $# -ne 1 ] && {
+[[ $# -ne 1 ]] && {
 	echo "Usage: ${name} name-of-kernel-module-file (without the .c)"
 	exit 1
 }
@@ -37,19 +44,19 @@ which lsb_release >/dev/null 2>&1 && {
 }
 echo -n "Kernel: " ; uname -r
 
-runcmd "sudo rmmod $1 2> /dev/null"
+runcmd "sudo rmmod $1 2> /dev/null" || true
 #runcmd "make clean"
-runcmd "sudo dmesg -C"
-runcmd "make || exit 1"
- # TODO - the '|| exit 1' does not seem to work
+runcmd "sudo dmesg -C" || true
+runcmd "make || exit 1" || true
 
-[ ! -f "$1".ko ] && {
-  echo "[!] ${name}: $1.ko has not been built, aborting..."
+[[ ! -f "$1".ko ]] && {
+  echo "[!] ${name}: \"$1.ko\" has not been built, aborting...
+(Note though, that this can happen when the module's named differently)."
   exit 1
 }
 
-runcmd "sudo insmod ./$1.ko && lsmod|grep $1"
+runcmd "sudo insmod ./$1.ko && lsmod|grep $1" || true
 # Ubuntu 20.10 onward has enabled CONFIG_SECURITY_DMESG_RESTRICT ! That's good for security
 # So we need to 'sudo' dmesg; thanks to @gregbuchholz for pointing this out
-runcmd "sudo dmesg"
+runcmd "sudo dmesg" || true
 exit 0
